fint:
  application-id: fint-kontroll-application-resource-gateway
  org-id: fintlabs.no
  kontroll:
    datainput: mock #fint
  resource-gateway:
    resources:
      entity:
        enabled: true
        refresh:
          interval-ms: 518400000
          topic-retention-time-offset-ms: 86400000
        pull:
          initial-delay-ms: 5000
          fixed-delay-ms: 900000
        entity-pipelines:
          - resource-reference: eiendeler.applikasjon.applikasjon
          - resource-reference: eiendeler.applikasjon.lisens
          - resource-reference: eiendeler.applikasjon.lisenstilgang
          - resource-reference: eiendeler.kodeverk.brukertype
          - resource-reference: eiendeler.kodeverk.lisensmodell
          - resource-reference: eiendeler.kodeverk.applikasjonskategori
          #- resource-reference: eiendeler.kodeverk.plattform

    authorization: disabled #enabled

  client:
    base-url: http://localhost:3000

    #base-url: http://fint-kontroll-mock-service:3000
    #base-url: https://beta.felleskomponent.no
    registration-id: fint
  kafka:
    default-replicas: 1
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
logging:
  level:
    root: INFO
    org.apache.kafka: INFO

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://login.microsoftonline.com/3d50ddd4-00a1-4ab7-9788-decf14a8728f/oauth2/v2.0/token
        registration:
          fint:
            client-secret:
            client-id: dummy
            authorization-grant-type: password
            provider: fint-idp
            scope: fint-client
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
server:
  port: 8089
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus